### ISSUE TITLE
exec scrim - server crash

### ISSUE THREAD

**Issue by mrc4tt** [marqdevx/mm-cs2-scrim#10]
Tested with MetaMod Source Version: 2.0-1256 & 2.0-1227

Executing scrim will make the server crash.
```
"Specialist<0><BOT><TERRORIST>" OnPreResetRound => CTMDBG, team 2  will switch 0 50.25 
"Aspirant<1><BOT><CT>" OnPreResetRound => CTMDBG, team 3  will switch 0 50.25 
./game/cs2.sh: line 118:    53 Segmentation fault      (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

My Scrim Config: [Scrim.cfg](https://gist.github.com/mrc4tt/ff29eafccc564d08baa554e1be16ccdd)

**Comment by marqdevx** [comment]
Does it crash with the CFG that I've included?

**Comment by mrc4tt** [comment]
> Does it crash with the CFG that I've included?

Nope, it doesn't crash at all.

**Comment by marqdevx** [comment]
Then try to check your cfg, let me know what was the issue if possible :D

**Comment by marqdevx** [comment]
I close the issue as in first instance it doesn't seem from the plugin side
