### ISSUE TITLE
Coach takes player spawns

### ISSUE THREAD

**Issue by messioso** [marqdevx/mm-cs2-scrim#14]
In scrim mode the coach spawns in normally, so they take up a spawn that would normally could be allocated to one of the 5 players, blocking them from having it. This effects the spawn randomisation making it different to a normal match.

A solution is to spawn the coach on a newly created spawn up in the air somewhere.

**Comment by marqdevx** [comment]
I know, I couldn't find how to do that yet. I'm still investigating 

I did it like this, to minimize the impact, as in case there are 5 competitive spawns, maximum only one player will not be in one of them

**Comment by marqdevx** [comment]
What I can do, is check all the spawns, and move the coach to a non-competitive spawn, and re-chech the players' spawns, in case some player is not in a competitive one, teleport him to a correct one.

Atleast we can make all the 5 players have the correct ones :)

**Comment by marqdevx** [comment]
Patch on new version
