### ISSUE TITLE
Gotv won't record

### ISSUE THREAD

**Issue by BH3Parthux** [marqdevx/mm-cs2-scrim#15]
Hey there, eventough I have gotv folder verygames/csgo/gotv 
, i cannot see my records in it. (of course i typed the command)

**Comment by marqdevx** [comment]
It should be `verygames/game/csgo/gotv/`

If that is right, type on the live console `tv_record test` to check that the GOTV is enabled

**Comment by BH3Parthux** [comment]
It says "GOTV[0]: Only GOTV Master can record demos instantly."

**Comment by marqdevx** [comment]
You need to enable gotv then
