### ISSUE TITLE
'metamod_oslink.h': No such file or directory (Windows)

### ISSUE THREAD

**Issue by AlexMougenet** [marqdevx/mm-cs2-scrim#18]
Hey
I would like to contribute to the project, but I'm having issues building the plugin on Windows

Here's the powershell script I'm using : 
```
git clone https://github.com/marqdevx/mm-cs2-scrim
cd mm-cs2-scrim
git submodule update --init --recursive
$env:MMSOURCE112="C:\Users\amougenet\Documents\mmsource-2.0.0-git1256-windows\addons\metamod"
$env:HL2SDKCS2="C:\Users\amougenet\Documents\mm-cs2-scrim\sdk"
mkdir build
cd build
python ../configure.py -s cs2
ambuild
```
And end up with this error after the `ambuild` command : 
```
C:\Users\amougenet\Documents\mm-cs2-scrim\src\utils\plat.h(22): fatal error C1083: Impossible d'ouvrir le fichier include�: 'metamod_oslink.h'�: No such file or directory
```

Any idea what I'm doing wrong ?
I can't find any `metamod_oslink.h` in mm-cs2-script, the sdk submodule, and the metamod:source build 1256

**Comment by marqdevx** [comment]
I've tried those commands and I dont get any issue.
How did you install ambuild? ´Env´ needs to be in caps though

**Comment by AlexMougenet** [comment]
I've followed [these steps](https://wiki.alliedmods.net/Ambuild#Installation) to install ambuild
I've changed `$env` into `$ENV` as you advised, as well as deleted the build folder for a new clean build
I now get this error : 
```
mm-cs2-scrim\src\cs2_sdk\../cs2fixes.h(22): fatal error C1083: Impossible d'ouvrir le fichier include�: 'ISmmPlugin.h'�: No such file or directory
```
I'm not familiar yet with metamod and ambuild. Maybe there is a hidden issue in my setup, and those errors are coming out
I'm still investigating on my side, thanks for your help !

**Comment by marqdevx** [comment]
I meant `Env`

You dont need metamod, atleast I dont have it on the env variables.

I've used this as reference, more clear IMO https://discord.com/channels/335290997317697536/1156576617968193597/1156849077888237598

**Comment by AlexMougenet** [comment]
It seems that the `$Env` [isn't case-sensitive](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3)

I don't have access to the discord link you sent
I've been using [Source2ZE/CS2Fixes](https://github.com/Source2ZE/CS2Fixes/#instructions) for the compilation instructions, but it might be difference for your project

**Comment by AlexMougenet** [comment]
I've followed the guide you sent and managed to fix my environment !
Here's what I did / changed : 

```
git clone https://github.com/marqdevx/mm-cs2-scrim
cd mm-cs2-scrim
git submodule update --init --recursive

git clone https://github.com/Kenzzer/ambuild.git
git clone --recursive https://github.com/alliedmodders/metamod-source.git
git clone --branch cs2 https://github.com/alliedmodders/hl2sdk.git hl2sdk-cs2

// wasn't sure which var name to choose for metamod
$Env:MMSOURCE_DEV="C:\Users\amougenet\Documents\mm-cs2-scrim\metamod-source"
$Env:MMSOURCE112="C:\Users\amougenet\Documents\mm-cs2-scrim\metamod-source"
$Env:HL2SDKCS2="C:\Users\amougenet\Documents\mm-cs2-scrim\hl2sdk-cs2"
pip install ./ambuild

mkdir build
cd build
python ../configure.py --sdks cs2 --targets x86_64
ambuild
```

I then had to update my Visual Studio because I had an old compiler

Thanks a lot 👍

**Comment by marqdevx** [comment]
Curiosity, are you working on an specific feature you want to contribute with? 👁️

**Comment by AlexMougenet** [comment]
Adding commands to place and control bots in practice (https://github.com/marqdevx/mm-cs2-scrim/issues/16)
However I'm only getting started and I'm not familiar with C++ yet, I may not succeed

**Comment by marqdevx** [comment]
Good luck!
Make a PR, even if it is a draft :D
