### ISSUE TITLE
Coach support

### ISSUE THREAD

**Issue by Porcellacion** [marqdevx/mm-cs2-scrim#2]
Amazing plugin. Coach support would be wonderful, how's the progress with that?

**Comment by marqdevx** [comment]
Hey! Thanks 😄 

I'm working on it, right now I'm stuck on trying to set the money to 0 on spawn (before killing the player on coach slot)

**Comment by Porcellacion** [comment]
I see, keep going, highly appreciated plugin :)

**Comment by lugaamn** [comment]
How to make the warmup period not valid until all players are ready?

**Comment by marqdevx** [comment]
@lugaamn what I do is typing .scrim and .pause until we all are ready, also you can be on .pracc mode while players are joining

Reminder that this plugin is for practice and not official matches :)

**Comment by Porcellacion** [comment]
Any progress on the coach feature? :)

**Comment by marqdevx** [comment]
Progress here https://github.com/marqdevx/mm-cs2-scrim/pull/9
Coach feature is working, I need to include all the stuff is already working on that branch

**Comment by marqdevx** [comment]
Released https://github.com/marqdevx/mm-cs2-scrim/releases/tag/v1.0.2
