### ISSUE TITLE
Configuration Issue in Building Project: SDK Support and Compiler Errors

### ISSUE THREAD

**Issue by dennisabrams** [marqdevx/mm-cs2-scrim#23]
## Issue Description
I'd like to start by mentioning that your Metamod addon works perfectly fine ❤️, which is greatly appreciated 👍. However, I've encountered an issue when attempting to build my own version of the addon. My primary goal is to make changes to some source files and compile the .so file for personal use.

During this process, I'm facing challenges due to the necessity of managing multiple SDKs and some difficulties with the available compilers on my system. These issues seem to be blocking the build process.

I'm facing an issue with the configuration process when trying to build a project using `ambuild2`. The process is halted due to an error related to SDK path configurations and compiler failures.

## Environment
- **Operating System:** Ubuntu 20.04.6 LTS (Focal)
- **Python Version:** 3.8.10
- **GCC Version:** 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)

## Steps to Reproduce
1. Installed `ambuild2` via Python's `pip`.
2. Cloned the `ambuild` repository from GitHub.
3. Installed `build-essential`.
4. Initially encountered error: `Configure failed: Could not find a valid path for HL2SDKCSGO`.
5. Executed `git submodule init` and `git submodule update`.
6. Set environment variable: `export HL2SDKCSGO=/home/dennis/mm-cs2-scrim/hl2sdk`.
7. Cloned [`hl2sdk`](https://github.com/alliedmodders/hl2sdk) from GitHub, checked out different branches (`blade`, etc.), and repeated similar steps for `HL2SDKDOTA` and `HL2SDKCS2`.
8. Encountered a recurring error when running `python3 configure.py`:

```
dennis@mail:~/mm-cs2-scrim$ python3 configure.py
Warning: build is being configured in the source tree.
Re-using build folder: objdir
Checking CC compiler (vendor test gcc)... ['clang', '-m32', 'test.c', '-o', 'test-c']
Compiler clang for CC failed: [Errno 2] No such file or directory: 'clang'
Checking CC compiler (vendor test gcc)... ['gcc', '-m32', 'test.c', '-o', 'test-c']
Compiler gcc for CC failed: Compiler failed with return code 1
Checking CC compiler (vendor test gcc)... ['icc', '-m32', 'test.c', '-o', 'test-c']
Compiler icc for CC failed: [Errno 2] No such file or directory: 'icc'
Skipping target x86: Unable to find a suitable C/C++ compiler
Checking CC compiler (vendor test gcc)... ['clang', '-m64', 'test.c', '-o', 'test-c']
Compiler clang for CC failed: [Errno 2] No such file or directory: 'clang'
Checking CC compiler (vendor test gcc)... ['gcc', '-m64', 'test.c', '-o', 'test-c']
found gcc version 9.4, x86_64
Checking CXX compiler (vendor test gcc)... ['g++', '-m64', 'test.cpp', '-o', 'test-cxx']
found gcc version 9.4, x86_64
Traceback (most recent call last):
  File "/home/dennis/.local/lib/python3.8/site-packages/ambuild2/frontend/v2_2/prep.py", line 156, in Configure
    if not cm.generate(options.generator):
  File "/home/dennis/.local/lib/python3.8/site-packages/ambuild2/frontend/context_manager.py", line 93, in generate
    self.parseBuildScripts()
  File "/home/dennis/.local/lib/python3.8/site-packages/ambuild2/frontend/v2_2/context_manager.py", line 50, in parseBuildScripts
    self.execContext(cx)
  File "/home/dennis/.local/lib/python3.8/site-packages/ambuild2/frontend/v2_2/context_manager.py", line 148, in execContext
    exec(code, scriptGlobals)
  File "/home/dennis/mm-cs2-scrim/AMBuildScript", line 521, in <module>
    MMSPlugin.detectSDKs()
  File "/home/dennis/mm-cs2-scrim/AMBuildScript", line 186, in detectSDKs
    raise Exception('Only one sdk at a time is supported, for multi-sdk approach use loader based solution.')
Exception: Only one sdk at a time is supported, for multi-sdk approach use loader based solution.
Configure failed: Only one sdk at a time is supported, for multi-sdk approach use loader based solution.
```

## Expected Behavior
I expected a seamless configuration process, allowing me to proceed with the build.

## Actual Behavior
The configuration fails, indicating issues with handling multiple SDKs and compiler failures.

## Additional Context
- The build process seems to be impeded by the necessity of handling multiple SDKs and issues with the available compilers on my system.
- My primary objective is to change certain source files and compile the `.so` file for my own use.

Would really appreciate any help with this. Thanks! :octocat:

**Comment by marqdevx** [comment]
Nice explanation and thanks for the words ♥

Then check out this file, I use that on linux, using a docker image which is the steam sniper image
https://github.com/marqdevx/mm-cs2-scrim/blob/main/docker-setup.sh

You are setting wrong the configuration:
1. use `python3 ../configure.py --sdks cs2 --targets x86_64`
2. set the correct env variable, something like `export HL2SDKCS2='/dockerVolume/mm-cs2-scrim/sdk'`

The image I'm using you can pull it with `docker pull registry.gitlab.steamos.cloud/steamrt/scout/sdk`
