### ISSUE TITLE
Add .help command

### ISSUE THREAD

**Issue by vmisel** [marqdevx/mm-cs2-scrim#24]
Could you please add a .help command that gives a list of all usable commands? Would be really helpful. I know them, but my teammates don't because they don't deal with the scripts etc.

Thank you.

**Comment by marqdevx** [comment]
Sounds good.

Returning the list for the current permissions the player has.

Wil do!

**Comment by lugaamn** [comment]
if there is no admin how to game start? Can players start the game after being on warmup and giving .ready? Please make warmup.cfg like Pugsetup and Get5

**Comment by marqdevx** [comment]
@lugaamn that plugin is oriented towards more automated matches, not private practice and scrims

**Comment by lugaamn** [comment]
Does it mean that you must be an administrator to start the game?

**Comment by vmisel** [comment]
> Sounds good.
> 
> Returning the list for the current permissions the player has.
> 
> Wil do!

Sounds perfect. What would be the best way to know when you've updated this. Can I subscribe to future updates by e-mail? I'm new to Github. Thanks again.

**Comment by marqdevx** [comment]
@vmisel check your configuration of notifications from github and on the repository you can mark the watch button, so you can set what to be notified by.
