### ISSUE TITLE
Wildcard for all players on the server

### ISSUE THREAD

**Issue by Gigelicious** [marqdevx/mm-cs2-scrim#25]
Hey, 

first of all, thats a very nice project! I installed it on my server and it works smoothly.

I got one question though, regarding to the rights player can have on the Server, which are configurated under `admin.cfg`: 

Is it possible to give all players on the server specific rights, like a wildcard to use the `.pracc` and `.scrim` command?`

`admin.cfg`:

````
{
    "name" 
    {
        "ip" "!0.0.0.0"         // All users from this IP
        "flags" "abcdefg"  // permission flags, same as sourcemod with z being everything
    }
}

**Comment by marqdevx** [comment]
Hey! Thanks :D
Right now it just allows to set the steamid there.
