### ISSUE TITLE
Q: Map change is delayed 5 seconds and printed globally

### ISSUE THREAD

**Issue by vmisel** [marqdevx/mm-cs2-scrim#29]
Where can I adjust this timer setting. I get the idea of a delay, but 5 seconds is very long. The print happens instantly, but the 5 seconds makes it seem like it's not working correctly, even though it is.

Furthermore, workshops maps are now able to be hosted on Linux servers, which I have through VeryGames. To test workshop maps i use the command host_workshop_map <MAPID>, so I want to actually be able to change the 5 seconds somewhere to something else. Preferrably 0.

**Comment by marqdevx** [comment]
I've added those 5 seconds of delay:
1. Let everyone know the map is going to change
2. If someone is checking something on practice mode, those few seconds can be used to finish the check, for example, checking a flash lineup  
   - I'm also thinking on an `.abort` command (only for admins) to cancel the map change
   
But making the timer configurable, seems ok, I will note it for the future :)
