### ISSUE TITLE
Round Knife Support

### ISSUE THREAD

**Issue by crashzk** [marqdevx/mm-cs2-scrim#3]
Can we expect support for Round Knife before competitive starts?

We start the competitive, the knife round takes place and the winning team can choose the team they want to play, CT or TR.

Choose your team via chat command, **!stay** or **!swap**.

**Comment by marqdevx** [comment]
For now I will not prioritize this.

Let me explain: This plugins is more oriented towards "competitive practice" where the minimalistic aproach is better, knife rounds are here to choose sides on an official match, but on a scrim, on which you have mr24 so you play the same amount of rounds on each side, it does not really make sense.

But in case I add a more "official match" oriented commands, I will for sure add this behavior!

On the other hand, adding `!swap` could be a good idea, to have the `mp_swapteams` command more handy.

Hope I explained myself clearly! 😄 
Thanks for asking!

**Comment by crashzk** [comment]
I see, thanks for the explanation.

In any case, I leave a suggestion for the plugin/script focused on Competitive, something like it has for CSGO - WarMod [BFG] | PUGSetup.

I believe that a plugin just for CS2 would be better, then we can focus on the round knife system, TAG on player nicknames and many other features.
