### ISSUE TITLE
.coach doesn't always seem to work

### ISSUE THREAD

**Issue by vmisel** [marqdevx/mm-cs2-scrim#31]
Hi,

The .coach option doesn't always seem to work. When our 6th presses .coach, how does it know what side we're on? Could you elaborate on this?

We can see "Coaching:" in front of his name, but he spawns with us and can shoot etc. Maybe it's on my end.

Thanks.

**Comment by marqdevx** [comment]
You need to manually chose the team.

For future updates, I will add a `.ct`, `.t` and `.spec` to have it more handy.
