### ISSUE TITLE
stop working when installed CounterStrikeSharp

### ISSUE THREAD

**Issue by meanwhiletothestars** [marqdevx/mm-cs2-scrim#32]
plugin stop working as soon as CounterStrikeSharp installed. Meta list indicates, that it works. No console issues report, no one command is working. Is this normal?

**Comment by meanwhiletothestars** [comment]
https://github.com/Source2ZE/CS2Fixes/pull/96

**Comment by marqdevx** [comment]
For now is not compatible with CounterStrikeSharp.

I will need to apply the changes you've pointed.
