### ISSUE TITLE
Plugin can't loaded

### ISSUE THREAD

**Issue by denrio157** [marqdevx/mm-cs2-scrim#34]
I've followed all the steps but when this is happen 

meta list
Listing 1 plugin:
  [01] <ERROR>

![image](https://github.com/marqdevx/mm-cs2-scrim/assets/31591836/460c2471-309e-498f-a3dd-98910d442331)

**Comment by marqdevx** [comment]
What version of metamod are you using?

**Comment by denrio157** [comment]
> What version of metamod are you using?

Ahh this issue, sorry i'm forget to resinstal or instal Microsoft Visual Studio Redistributables.. but now is working, but when i try instal CSS your mod can't work.. why? it should be move mmcs2scrim to plugin CSS or what?

**Comment by marqdevx** [comment]
Cool.

CSS and this plugin share some stuff, so they are not compatible at the moment
