### ISSUE TITLE
Question? !bot commands

### ISSUE THREAD

**Issue by dvgmdvgm** [marqdevx/mm-cs2-scrim#35]
Hello! Want to ask about !bot, !boost, !crouchboost commands.
Will it implemented in your mod? Because only one commands I need to use on practice server and now I can't find any plugins to use it except only PRACC dedicated server which I have to pay 20 bucks every month.
Maybe I can buy onetime this dedicated server from PRACC and you can try to get this !bot features from their practice server if I will pay for this server? Or something else

**Comment by marqdevx** [comment]
I will implement it soon, right now im focusing on fixing the coach an adding util and damage info.

This plugin has that already implemented https://github.com/shobhit-pathak/MatchZy
