### ISSUE TITLE
`c_reload_admins` crashes the server

### ISSUE THREAD

**Issue by x7airworker** [marqdevx/mm-cs2-scrim#36]
OS: Debian 11

When used without players on the server the command works fine.
After I join and reload the admins, the server crashes.
- I've updated to the newest `cs2fixes.games.txt`.
- I've got it to work once.

admins.cfg:
```
Admins
{
    "Jake" // can be anything
    {
        "steam" "<my-steam-id>" // steamid64
        "flags" "z" // permission flags, same as sourcemod with z being everything
    }
}
```

The issue might be related to the following line changed in CS2Fixes: https://github.com/Source2ZE/CS2Fixes/blob/main/src/adminsystem.cpp#L73

**Comment by marqdevx** [comment]
Please try this pre-release version https://github.com/marqdevx/mm-cs2-scrim/releases/tag/1.0.3.0-beta
It is not crashing my SV

**Comment by x7airworker** [comment]
Unfortunately this didn't fix the issue, but I've found a way to consistenly reproduce the issue: Join the server and immediately run the command, before the player is authenticated.

**Comment by marqdevx** [comment]
Are you triggering it by chat?
After joining a team?

**Comment by x7airworker** [comment]
Triggering by server console; doesn't matter if I join a team.
I think the issue is fixed by the additional condition which I linked in the CS2Fixes admin system.
The condition checks if the player isn't authenticated and then skips.

**Comment by marqdevx** [comment]
I am not getting any crash using the server console, but I will add it for the next release, it is not urgent.

**Comment by marqdevx** [comment]
Okay, I found why, steam is not login fast enough, so it gets crashed, now it is urgent ahhahhaha

**Comment by marqdevx** [comment]
Patch on new version
