### ISSUE TITLE
Plugin doesn't work because of new update?

### ISSUE THREAD

**Issue by puma8917** [marqdevx/mm-cs2-scrim#40]
Hello,

I installed the plugin. It worked normaly until the update, Are there issues with the new update?

Here is the console command answer when I type "meta list"

09.02 19:07:26 [Server] INFO meta list
09.02 19:07:26 [Server] INFO Listing 1 plugin:
09.02 19:07:26 [Server] INFO [01] <ERROR>

Regards
Puma

**Comment by realm0b** [comment]
Hi, 

Same problem here.

Command: meta list
Response: Listing 1 plugin:
  [01] <ERROR>

Greetings
mOb

**Comment by marqdevx** [comment]
Yes, I need to re-compile it and maybe fix some line of code.
I'll let you know tomorrow, I will also release the new version with this hotfix.

**Comment by marqdevx** [comment]
You have more info at #41 
Have a nice one 🤙
