### ISSUE TITLE
Plugin error while launching the server

### ISSUE THREAD

**Issue by Rockstar234** [marqdevx/mm-cs2-scrim#41]
Fresh installed server, but when I launch it error pops up. What's wrong?
![image](https://github.com/marqdevx/mm-cs2-scrim/assets/81024464/dca14ad7-e63e-4d9c-aec8-21d28820ec3e)

**Comment by marqdevx** [comment]
Hi, yes currently the plugin is not working after the latest updates, I'm working on the update, but it's gonna take a few days, I'm basically rebasing from CS2Fixes completely so it's like starting from scratch and then, adding my additions again.

Apologies for it :(

**Comment by Rockstar234** [comment]
> Hi, yes currently the plugin is not working after the latest updates, I'm working on the update, but it's gonna take a few days, I'm basically rebasing from CS2Fixes completely so it's like starting from scratch and then, adding my additions again.
> 
> Apologies for it :(

yikes. take your time, hope everything goes smoothly👍🏼
thanks for answer

**Comment by marqdevx** [comment]
Thanks, I appreciate your words :D

I think the fix is coming soon, im still working on it, but idk whats really happening atm :(
Im still investigating

**Comment by marqdevx** [comment]
Fixed the issue, im doing the needed fixes here https://github.com/marqdevx/mm-cs2-scrim/pull/42 which will be added to https://github.com/marqdevx/mm-cs2-scrim/pull/38 for the new release adding also new features

I will close the issue once the new version is released 😄

**Comment by marqdevx** [comment]
Try the zip available here https://github.com/marqdevx/mm-cs2-scrim/actions/runs/8118334766

**Comment by Rockstar234** [comment]
> Try the zip available here https://github.com/marqdevx/mm-cs2-scrim/actions/runs/8118334766

Will try it out today, I guess in some hours. Thanks!

**Comment by Rockstar234** [comment]
It works, but it launches as a normal match for some reason. Also, it says that I dont have access to commands (yes, I edited admins list correctly, with flag "z")

**Comment by marqdevx** [comment]
I cannot compile it on windows, i have issues only there, I will take care of them soon

Send the admins cfg text here, so I can check :)

**Comment by Rockstar234** [comment]
```
Admins
{
    "name" // can be anything
    {
        "steamid" "76561199383412696" // steamid64
        "flags" "z" // permission flags, same as sourcemod with z being everything
    }
}
```

**Comment by Rockstar234** [comment]
even if I execute commands via console server doesnt even care, its still normal not modded comp match

**Comment by marqdevx** [comment]
use "steam" instead of "steamid"

**Comment by Rockstar234** [comment]
> use "steam" instead of "steamid"

Okay. Gonna try it. What about other problems? Any ideas? :D

**Comment by marqdevx** [comment]
Is the plugin showing when you type `meta list`?

**Comment by Rockstar234** [comment]
> Is the plugin showing when you type `meta list`?

Yep sure

**Comment by marqdevx** [comment]
Then I dont get the issue
Are only the admin commands not working?

**Comment by Rockstar234** [comment]
> Then I dont get the issue Are only the admin commands not working?

I'll send you screenshots or clip later.

**Comment by Rockstar234** [comment]
> Then I dont get the issue Are only the admin commands not working?

Okay. Now it works KEKW
Would be really nice to see auto setup of unlimited warmup before every player gets "!ready" and etc (features like eBot/FaceIT always had yk). Great job, looks good for beta!

**Comment by marqdevx** [comment]
Fixed the windows compilations
Feel free to try it out https://github.com/marqdevx/mm-cs2-scrim/actions/runs/8131110048

**Comment by Rockstar234** [comment]
> Fixed the windows compilation Feel free to try it out https://github.com/marqdevx/mm-cs2-scrim/actions/runs/8131110048

It launched, but gonna test it more tomorrow

**Comment by marqdevx** [comment]
Sure re-open the ticket if you get any crash
