### ISSUE TITLE
Spawns missing / not working and admins.cfg mistake

### ISSUE THREAD

**Issue by xaddey** [marqdevx/mm-cs2-scrim#45]
Hi

Thanks for the great plugin.
The .spawns on mirage are not working properly / are missing.
On T Side 3-4-5 are working, with the rest it doesn't work at all.
example:

 .spawn 2 
"[CS2Scrim] You have been teleported to spawn. 2/10 priority:0"

But i won't get teleported. Probably outdated spawns?
I might try to update them myself.

And when i tried to add admins to "admins.cfg" it had "steamid" instead of "steam"
which would prevent it from actually load the admins.

best regards

edit: 

Versions

  [01] CS2Scrim (1.1.0-beta) by marqdevx (ρλd)

meta version
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1282
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Feb  7 2024 19:09:08
    Built from: https://github.com/alliedmodders/metamod-source/commit/3740821
    Build ID: 1282:3740821
    http://www.metamodsource.net/

**Comment by marqdevx** [comment]
Try this one https://github.com/marqdevx/mm-cs2-scrim/releases/tag/1.1.0-beta

**Comment by marqdevx** [comment]
Ive checked and yes, i have the same issue, idk why

The plugin looks the spawn entities and just use the competitive ones, in theory

I will check

**Comment by marqdevx** [comment]
I am getting this on mirage

T Spawns
```
Spawn 0: 1296.000000 / -352.000000 / -144.000000
Spawn 1: 1296.000000 / 32.000000 / -144.000000
Spawn 2: 1216.000000 / -16.000000 / -144.000000
Spawn 3: 1216.000000 / -115.000000 / -144.000000
Spawn 4: 1216.000000 / -211.000000 / -144.000000
Spawn 5: 1216.000000 / -307.000000 / -144.000000
Spawn 6: 1136.000000 / -256.000000 / -144.000000
Spawn 7: 1136.000000 / -160.000000 / -144.000000
Spawn 8: 1136.000000 / -64.000000 / -144.000000
Spawn 9: 1136.000000 / 32.000000 / -144.000000
```
CT Spawns
```
Spawn 0: -1776.000000 / -1976.000000 / -240.000000
Spawn 1: -1776.000000 / -1800.000000 / -240.000000
Spawn 2: -1720.000000 / -1896.000000 / -240.000000
Spawn 3: -1656.000000 / -1800.000000 / -240.000000
Spawn 4: -1656.000000 / -1976.000000 / -240.000000
```
But I don't understand why it does not teleport

Then on inferno CT side, I also get 6 spawn points
```
Spawn 0: 2493.000000 / 2090.000000 / 140.843002
Spawn 1: 2456.830078 / 2153.159912 / 140.843002
Spawn 2: 2472.349854 / 2005.969971 / 140.843002
Spawn 3: 2353.000000 / 1977.000000 / 140.843002
Spawn 4: 2292.060059 / 2027.689941 / 140.843002
Spawn 5: 2397.000000 / 2079.000000 / 155.000000
```
On this case, the only one which doesnt work is the Spawn 5 (the 6th)

**Comment by marqdevx** [comment]
Using this https://github.com/marqdevx/mm-cs2-scrim/blob/marqdevx/1.1.0/src/cs2_sdk/entity/cbaseentity.h#L144 function isntead of setting the pos, seems to successfully teleport the player

**Comment by marqdevx** [comment]
Test on the sv with the following package https://github.com/marqdevx/mm-cs2-scrim/actions/runs/8157417369?pr=44
