### ISSUE TITLE
Admin not loading

### ISSUE THREAD

**Issue by M0n-k3y** [marqdevx/mm-cs2-scrim#46]
I edited the file /csgo/game/csgo/addons/cs2scrim/configs admin.cfg but i still have no access as admin

**Comment by BluePineappleCake** [comment]
![Screenshot 2024-03-06 180106](https://github.com/marqdevx/mm-cs2-scrim/assets/92988597/d651808b-6707-49c4-ad91-63c57a53839d)

You have to change your steamid to match yours and *probably an oversight, change steamid to steam like you see in my screenshot.
Then just type c_reload_admins in the server console

**Comment by marqdevx** [comment]
@BluePineappleCake is right, I need to update the admins.cfg

the field for the steam id should be `steam` on the file included is `steamid` which is wrong

**Comment by marqdevx** [comment]
I am gonna make a compatibility fix, so both "steam" and "steamid" will be valid

As other plugins use it I think it is better to have both :)
