### ISSUE TITLE
Demo not saving in gotv in FTP folder

### ISSUE THREAD

**Issue by vmisel** [marqdevx/mm-cs2-scrim#5]
The demo doesn't get saved in the gotv map on the verygames FTP server. I tried .record and 15 seconds after .stoprecord. 

/edit: The .record and .stoprecord commands do work and I see the feedback in the game chat.

Anything I am doing wrong?

**Comment by Porcellacion** [comment]
You must have GOTV enabled, and make sure tv_autorecord is disabled.
This works great on DatHost

**Comment by vmisel** [comment]
Could you explain the steps needed to take? So:

- How do I enable GOTV?
- In what cfg could I add the tv_autorecord 0 or false (I assume)? Would that be server.cfg?

**Comment by marqdevx** [comment]
You can exec the CFG that I include on the zip
After that it should be enabled

**Comment by vmisel** [comment]
Works now! Restarted the server.

What I did was:
added exec gotvcfg.cfg to server.cfg, so I won't have to do it manually every time. Restarted server.

Changed also some settings in the gotvcfg.cfg like tv name and the tv_snapshotrate to 64
