### ISSUE TITLE
Error while opening.

### ISSUE THREAD

**Issue by romerocox** [marqdevx/mm-cs2-scrim#57]
![image](https://github.com/marqdevx/mm-cs2-scrim/assets/29244464/032b9960-c95b-4753-9505-11e4741e934c)

Any assistance is much appreciated. 

"cs2.exe - Entry Point Not Found
The procedure entry point ?EnterScope@CVProfile@@QEAAXPEBDH0_N@Z could not be located in the dynamic link library C:\Program Files (x86)\Steam\steamapps\common\CS2_DEV\game\csgo\addons\cs2scrim\bin\win64\cs2scrim.dll.
"

when I run meta list:

meta list
Listing 2 plugins:
  [01] CounterStrikeSharp (v0 @ 11e5e99) by Roflmuffin
  [02] <ERROR>

MM Details Windows:

meta version
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1290
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Apr 30 2024 16:20:47
    Built from: https://github.com/alliedmodders/metamod-source/commit/3d466fd
    Build ID: 1290:3d466fd
    http://www.metamodsource.net/
  
  this is also happening within my lynux environment which is running:
  
  Metamod:Source Version Information Metamod:Source version 2.0.0-dev+1291 Plugin interface version: 16:14 SourceHook version: 5:5 Loaded As: GameDLL (gameinfo.txt) Compiled on: Apr 30 2024 16:22:46 Built from: https://github.com/alliedmodders/metamod-source/commit/607301a Build ID: 1291:607301a http://www.metamodsource.net/

**Comment by marqdevx** [comment]
It should now be fixed by this merge #52 
Check the https://github.com/marqdevx/mm-cs2-scrim/releases/tag/1.1.3  version

**Comment by romerocox** [comment]
Rockstars! Thanks!
