### ISSUE TITLE
Skins and weapon loadout missing

### ISSUE THREAD

**Issue by vmisel** [marqdevx/mm-cs2-scrim#6]
Every few matches we lose all our skins and weapon loadouts.

**Comment by Porcellacion** [comment]
This is not a plugin-related issue, this is due to the CS2 dedicated server binaries.

**Comment by vmisel** [comment]
Thank you for clarifying. Any advise you might have to fix this? You can close the thread after.

Thanks again.

**Comment by marqdevx** [comment]
I don't have any suggestion unfortunately, feel free to share it here once you fix it
