### ISSUE TITLE
Windows error when load plugin

### ISSUE THREAD

**Issue by JoShMiQueL** [marqdevx/mm-cs2-scrim#7]
When list plugins with meta show <NOFILE>
[Image 1](https://imgur.com/a/WfY9nEt)
[Image 2](https://imgur.com/a/A5aCCId)

**Comment by marqdevx** [comment]
You are right, I didn't make the zip file for windows correctly, I'll fix it

**Comment by marqdevx** [comment]
Retry now https://github.com/marqdevx/mm-cs2-scrim/releases/tag/v1.0.0
